import React, {useState, useRef, useCallback} from 'react';
import {View, Text, TouchableOpacity, StyleSheet, ActivityIndicator} from 'react-native';
import Video from 'react-native-video';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import {kidsColors, kidsSpacing, kidsBorderRadius, kidsFontSize, kidsFontWeight, kidsShadows} from '../../../../../theme/kidsColors';

/**
 * KidsVideoPlayer - Kid-friendly video player wrapping react-native-video.
 *
 * Large, colorful controls designed for small fingers.
 * Used for educational videos generated by LTX2 backend.
 *
 * Props:
 * - source: { uri: string } - Video source (file path or URL)
 * - onEnd: () => void - Called when video finishes
 * - autoPlay: boolean (default true)
 * - showControls: boolean (default true)
 * - poster: string - Poster image URI
 * - style: ViewStyle
 */
const KidsVideoPlayer = ({source, onEnd, autoPlay = true, showControls = true, poster, style}) => {
  const videoRef = useRef(null);
  const [paused, setPaused] = useState(!autoPlay);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [progress, setProgress] = useState(0);
  const [duration, setDuration] = useState(0);

  const handleLoad = useCallback((data) => {
    setLoading(false);
    setDuration(data.duration || 0);
  }, []);

  const handleProgress = useCallback((data) => {
    if (data.currentTime && duration > 0) {
      setProgress(data.currentTime / duration);
    }
  }, [duration]);

  const handleEnd = useCallback(() => {
    setPaused(true);
    setProgress(1);
    if (onEnd) onEnd();
  }, [onEnd]);

  const handleError = useCallback(() => {
    setError(true);
    setLoading(false);
  }, []);

  const togglePlayPause = useCallback(() => {
    if (progress >= 1) {
      // Restart
      videoRef.current?.seek(0);
      setProgress(0);
    }
    setPaused(prev => !prev);
  }, [progress]);

  if (error) {
    return (
      <View style={[styles.container, styles.errorContainer, style]}>
        <Icon name="video-off" size={48} color={kidsColors.textMuted} />
        <Text style={styles.errorText}>Video not available</Text>
      </View>
    );
  }

  return (
    <View style={[styles.container, style]}>
      <Video
        ref={videoRef}
        source={source}
        style={styles.video}
        paused={paused}
        resizeMode="contain"
        onLoad={handleLoad}
        onProgress={handleProgress}
        onEnd={handleEnd}
        onError={handleError}
        poster={poster}
        posterResizeMode="contain"
        repeat={false}
      />

      {loading && (
        <View style={styles.loadingOverlay}>
          <ActivityIndicator size="large" color={kidsColors.accent} />
          <Text style={styles.loadingText}>Loading video...</Text>
        </View>
      )}

      {showControls && !loading && (
        <View style={styles.controls}>
          <TouchableOpacity
            style={styles.playButton}
            onPress={togglePlayPause}
            activeOpacity={0.7}
            accessibilityLabel={paused ? (progress >= 1 ? 'Replay video' : 'Play video') : 'Pause video'}
            accessibilityRole="button"
          >
            <Icon
              name={paused ? (progress >= 1 ? 'replay' : 'play') : 'pause'}
              size={32}
              color={kidsColors.textOnDark}
            />
          </TouchableOpacity>

          {/* Progress bar */}
          <View style={styles.progressBar}>
            <View style={[styles.progressFill, {width: `${progress * 100}%`}]} />
          </View>
        </View>
      )}

      {/* Big center play button when paused */}
      {paused && !loading && (
        <TouchableOpacity
          style={styles.centerPlayButton}
          onPress={togglePlayPause}
          activeOpacity={0.7}
          accessibilityLabel={progress >= 1 ? 'Replay video' : 'Play video'}
          accessibilityRole="button"
        >
          <View style={styles.centerPlayCircle}>
            <Icon
              name={progress >= 1 ? 'replay' : 'play'}
              size={48}
              color={kidsColors.textOnDark}
            />
          </View>
        </TouchableOpacity>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    borderRadius: kidsBorderRadius.lg,
    overflow: 'hidden',
    backgroundColor: '#000',
    aspectRatio: 16 / 9,
    ...kidsShadows.card,
  },
  video: {
    width: '100%',
    height: '100%',
  },
  errorContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: kidsColors.card,
    gap: kidsSpacing.sm,
  },
  errorText: {
    fontSize: kidsFontSize.md,
    color: kidsColors.textMuted,
    fontWeight: kidsFontWeight.medium,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
    gap: kidsSpacing.sm,
  },
  loadingText: {
    fontSize: kidsFontSize.sm,
    color: '#fff',
    fontWeight: kidsFontWeight.medium,
  },
  controls: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    padding: kidsSpacing.sm,
    backgroundColor: 'rgba(0,0,0,0.4)',
    gap: kidsSpacing.sm,
  },
  playButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: kidsColors.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressBar: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.3)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: kidsColors.accent,
    borderRadius: 4,
  },
  centerPlayButton: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerPlayCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: kidsColors.accent + 'CC',
    justifyContent: 'center',
    alignItems: 'center',
    ...kidsShadows.float,
  },
});

export default KidsVideoPlayer;
